# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8bcc3eef23fe2b28204fa290f191c8c6c864fbf61d44b6c853f3d5a9c6645fd904ab1e2138bed19717de3a13099746e99b8f105d993bb468415f21dccd89fce1

test:
  secret_key_base: 3f4e36ef24b7259b0111371813109e4cfc065973f6cd92935eeac5a6e15305151f460894f14c2726b23e66a41e5bb6eaf09bdc80c68e4681382bfa0d16694c46

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
